# Generated by Django 2.2.5 on 2020-01-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_detail_game_overview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='game',
        ),
    ]
