# Generated by Django 2.2.5 on 2020-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_controll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField()),
                ('game_round', models.PositiveIntegerField()),
                ('game_status', models.PositiveIntegerField()),
            ],
        ),
    ]
