# Generated by Django 2.2.5 on 2020-01-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_controll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_overview',
            name='is_activate',
        ),
    ]
